version: "2"
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - cluster.name=hive
      - thread_pool.search.queue_size=100000
      - gateway.recover_after_nodes=1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  cortex:
    image: thehiveproject/cortex:3.0.0
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:3.4.0
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
